project:
  type: book
  output-dir: docs

book:
  title: "DS2023 Final Project (Rename)"
  author: "Jessica Ni, Maya Uwaydat, Wissal Khlouf"
  favicon: logo.png
  description: An outline for the DS2023 Communicating with Data final project report.
  keyword: data science, aclr
  url: https://mayooueidat-uva.github.io/ACLR-group-project/
  sidebar:
    logo: logo.png
    search: true
  repo-url: https://github.com/mayooueidat-uva/ACLR-group-project/tree/main
  repo-branch: master
  image: logo.png

  chapters:
    - index.qmd
    - ./EDA/datacleaning_forbook.qmd
    - ./EDA/Group_EDA_addchangeshere_ver2.qmd
    - ./Graphs/Visualizations_book.qmd
    - ./datadictionary.qmd

format:
  html:
    theme:
      - minty
    code-fold: false
    #backgroundcolor: "#fafeff"
  #pdf:
  #  documentclass: scrreprt
